// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Button$ReactHooksTemplate from "./Button.bs.js";

((require('./Login.css')));

function Login(Props) {
  var match = React.useState((function () {
          return "";
        }));
  var setEmail = match[1];
  var match$1 = React.useState((function () {
          return "";
        }));
  var setPassword = match$1[1];
  var handleEmailChange = function (e) {
    return Curry._1(setEmail, e.target.value);
  };
  var handlePasswordChange = function (e) {
    return Curry._1(setPassword, e.target.value);
  };
  var handleFormSubmit = function (e) {
    e.preventDefault();
    return /* () */0;
  };
  return React.createElement("div", {
              className: "Login"
            }, React.createElement("h2", undefined, "Login"), React.createElement("form", {
                  onSubmit: handleFormSubmit
                }, React.createElement("div", {
                      className: "inputField"
                    }, React.createElement("input", {
                          placeholder: "Email",
                          required: true,
                          type: "email",
                          value: match[0],
                          onChange: handleEmailChange
                        })), React.createElement("div", {
                      className: "inputField"
                    }, React.createElement("input", {
                          placeholder: "Password",
                          required: true,
                          type: "password",
                          value: match$1[0],
                          onChange: handlePasswordChange
                        })), React.createElement(Button$ReactHooksTemplate.make, {
                      title: "Login",
                      children: "Login",
                      category: /* PRIMARY */0
                    })));
}

var make = Login;

export {
  make ,
  
}
/*  Not a pure module */
